name: hello-workflows
on:
        push:
                branches:
                        - main  
        pull_request:
                branches:
                        - main
        workflow_dispatch:

jobs:
        hello:
                runs_on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: hello world
                          run: echo "Hello world"
                          shell: bash
        goodbye:
                runs_on: ubuntu_latest
                steps:
                        - name : goodbye
                          run: echo "GoodBye<><><>"
                          shell: bash

