name: test-workflow
on:
        push:
                branches:
                        - main
        pull_request:
                branches:
                        - main
jobs:
        first_job:
                runs-on: ubunu-latest
                steps:
                        - uses : actions/checkout@v2
                        - name: test
                          shell: bash
                          run : whoami

